[task-7] DB
ozonva/ova-recipe-api pull request #7
Opened 2021-08-30 05:51 UTC by f0rtung

2021-08-30 06:34 UTC, siriusfreak requested changes
Также не вижу тестов для репо

2021-08-30 06:34 UTC, siriusfreak commented on Dockerfile
> +FROM golang:1.17.0-buster
Как упражнение -- сделать билд в одном контейнере, где есть нужное окружение, а запуск в другом, где просто собранный бинарник.

2021-08-30 06:34 UTC, siriusfreak commented on Dockerfile
> +COPY ./cmd /opt/cmd
Как-то не очень, а если ещё папки появятся? 

Можешь попробовать .Dockerignore файл сделать

2021-08-30 06:34 UTC, siriusfreak commented on db/dbconf.yaml
> +development:
Если есть файл конфига, то может сюда и DSN?

2021-08-30 06:34 UTC, siriusfreak commented on db/migrations/20210829164236_init_db.sql
> +create table recipe (
Не знаю обсуждали или нет, но тут имеет смысл писать if exists. Потому что миграции на прод имеет смысл накатывать в ручном режиме. Как минимум потому, что goose всё оборачивает в транзакции и нет возможности создать индекс в конкурентном режиме, т.е. не блокируя всю таблицу.

2021-08-30 06:34 UTC, siriusfreak commented on docker-compose.yml
> +services:
Сюда можно допиать и контейнер с приложением, раз ты сделал к нему докерфайл

2021-08-30 16:48 UTC, f0rtung commented on Dockerfile
> +FROM golang:1.17.0-buster
Сделал в рамках 6й задачи.

2021-08-30 16:48 UTC, f0rtung commented on Dockerfile
> +COPY ./cmd /opt/cmd
Просто копирую все содержимое проекта.

2021-08-30 16:58 UTC, f0rtung commented on db/migrations/20210829164236_init_db.sql
> +create table recipe (
Видимо, речь о if NOT exists. Добавил.

2021-08-30 17:24 UTC, f0rtung commented on docker-compose.yml
> +services:
Сделал.

2021-08-31 05:12 UTC, f0rtung commented on db/dbconf.yaml
> +development:
Попробовал, но что-то не очень понравилось :( Переделал на простой env файл.

2021-08-31 06:49 UTC, siriusfreak approved these changes

2021-08-31 06:49 UTC, merged